build_image:
    image: docker:1.12.3
    services:
        - docker:1.12.3-dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
        - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    only:
        - master
        - develop